In [24]:
import scipy.io
import pandas as pd
from caim import CAIMD

In [25]:
datasetFileName = 'Isolet.mat'

In [26]:
inp = './datasets/' + datasetFileName
mat = scipy.io.loadmat(inp)

In [27]:
#mat = {k:v for k, v in mat.items() if k[0] != '_'}
#data = pd.DataFrame({k: pd.Series(v[0]) for k, v in mat.iteritems()})
#mat = {k: v for k, v in mat.items() if not k.startswith('__')}
#data = pd.DataFrame({k: pd.Series(v[0]) for k, v in mat.items()})
#data.to_csv(out)
mat = {k:v for k, v in mat.items() if k[0] != '_'}
data = pd.DataFrame({k: pd.Series(v[0]) for k, v in mat.items()})

In [28]:
data.head()

        X    Y
0 -0.4394  1.0
1 -0.0930  NaN
2  0.1718  NaN
3  0.4620  NaN
4  0.6226  NaN

In [29]:
mat

{'X': array([[-0.4394, -0.093 ,  0.1718, ...,  0.641 ,  0.5898, -0.4872],
        [-0.4348, -0.1198,  0.2474, ...,  0.4318,  0.4546, -0.091 ],
        [ 0.0362,  0.751 ,  0.7188, ..., -0.0148, -0.3676, -0.7942],
        ...,
        [-0.2776,  0.2344,  0.8278, ...,  0.0184, -0.1902, -0.3988],
        [-0.1514,  0.2626,  0.8922, ..., -0.0646,  0.    , -0.4516],
        [-0.347 , -0.047 ,  0.6442, ...,  0.3058,  0.2066, -0.124 ]]),
 'Y': array([[ 1],
        [ 1],
        [ 1],
        ...,
        [26],
        [26],
        [26]], dtype=uint8)}

In [30]:
p = mat["X"]
q = mat["Y"]

In [31]:
df = pd.DataFrame(p)

In [32]:
df

,0,1,2,3,4,5,6,7,8,9,...,607,608,609,610,611,612,613,614,615,616
0,-0.4394,-0.0930,0.1718,0.4620,0.6226,0.4704,0.3578,0.0478,-0.1184,-0.2310,...,0.3334,0.4102,0.2052,0.3846,0.3590,0.5898,0.3334,0.6410,0.5898,-0.4872
1,-0.4348,-0.1198,0.2474,0.4036,0.5026,0.6328,0.4948,0.0338,-0.0520,-0.1302,...,0.2272,0.0000,0.2954,0.2046,0.4772,0.0454,0.2046,0.4318,0.4546,-0.0910
2,0.0362,0.7510,0.7188,1.0000,0.9358,0.9840,0.8072,0.4338,0.2290,0.2088,...,0.3824,0.2206,0.5882,0.4412,-0.1470,-0.0148,0.0294,-0.0148,-0.3676,-0.7942
3,0.0220,0.6740,0.6082,0.9122,0.7680,1.0000,0.7932,0.5204,0.1786,0.1568,...,0.3784,0.1216,0.2162,-0.0270,-0.1352,-0.1756,-0.4730,-0.3648,-0.3648,-0.4864
4,-0.9100,-0.3870,-0.3066,0.2048,0.1928,0.6852,0.5644,0.2782,0.1810,0.2072,...,-0.2632,0.0000,-0.2808,-0.4736,-0.3508,-0.3860,-0.4210,-0.2280,-0.3860,-0.5614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1555,-0.0530,0.4206,1.0000,0.9814,-0.0778,-0.3084,-0.3208,-0.5016,-0.5514,-0.5700,...,-0.0802,-0.1094,-0.0218,-0.0218,-0.0510,-0.2700,-0.2700,-0.2116,-0.2700,-0.4598
1556,-0.2220,0.2000,0.9692,1.0000,0.2176,-0.0506,-0.2176,-0.3230,-0.2396,-0.1780,...,0.3866,0.3334,0.3600,0.5200,0.9200,0.7866,0.5200,0.2000,0.4400,0.1734
1557,-0.2776,0.2344,0.8278,1.0000,0.6364,-0.0862,-0.2966,-0.4066,-0.5168,-0.3588,...,-0.2760,-0.0798,-0.0920,-0.0184,0.4110,0.4234,0.1288,0.0184,-0.1902,-0.3988
1558,-0.1514,0.2626,0.8922,0.8886,-0.1966,-0.4714,-0.4608,-0.7670,-0.6244,-0.5548,...,0.9032,1.0000,0.8870,0.1774,0.1612,0.2580,0.3870,-0.0646,0.0000,-0.4516
1559,-0.3470,-0.0470,0.6442,0.6442,-0.2412,-0.5058,-0.5176,-0.3676,-0.4882,-0.6058,...,0.5702,0.7520,0.9338,0.5042,0.2396,0.2396,0.3058,0.3058,0.2066,-0.1240

In [33]:
ff = pd.DataFrame(q)

In [34]:
ff

       0
0      1
1      1
2      1
3      1
4      1
...   ..
1555  26
1556  26
1557  26
1558  26
1559  26

[1560 rows x 1 columns]

In [35]:
ff.head

<bound method NDFrame.head of        0
0      1
1      1
2      1
3      1
4      1
...   ..
1555  26
1556  26
1557  26
1558  26
1559  26

[1560 rows x 1 columns]>

In [36]:
df.head

<bound method NDFrame.head of          0       1       2       3       4       5       6       7       8    \
0    -0.4394 -0.0930  0.1718  0.4620  0.6226  0.4704  0.3578  0.0478 -0.1184
1    -0.4348 -0.1198  0.2474  0.4036  0.5026  0.6328  0.4948  0.0338 -0.0520
2     0.0362  0.7510  0.7188  1.0000  0.9358  0.9840  0.8072  0.4338  0.2290
3     0.0220  0.6740  0.6082  0.9122  0.7680  1.0000  0.7932  0.5204  0.1786
4    -0.9100 -0.3870 -0.3066  0.2048  0.1928  0.6852  0.5644  0.2782  0.1810
...      ...     ...     ...     ...     ...     ...     ...     ...     ...
1555 -0.0530  0.4206  1.0000  0.9814 -0.0778 -0.3084 -0.3208 -0.5016 -0.5514
1556 -0.2220  0.2000  0.9692  1.0000  0.2176 -0.0506 -0.2176 -0.3230 -0.2396
1557 -0.2776  0.2344  0.8278  1.0000  0.6364 -0.0862 -0.2966 -0.4066 -0.5168
1558 -0.1514  0.2626  0.8922  0.8886 -0.1966 -0.4714 -0.4608 -0.7670 -0.6244
1559 -0.3470 -0.0470  0.6442  0.6442 -0.2412 -0.5058 -0.5176 -0.3676 -0.4882

         9    ...     607     608     609     610     611     612     613  \
0    -0.2310  ...  0.3334  0.4102  0.2052  0.3846  0.3590  0.5898  0.3334
1    -0.1302  ...  0.2272  0.0000  0.2954  0.2046  0.4772  0.0454  0.2046
2     0.2088  ...  0.3824  0.2206  0.5882  0.4412 -0.1470 -0.0148  0.0294
3     0.1568  ...  0.3784  0.1216  0.2162 -0.0270 -0.1352 -0.1756 -0.4730
4     0.2072  ... -0.2632  0.0000 -0.2808 -0.4736 -0.3508 -0.3860 -0.4210
...      ...  ...     ...     ...     ...     ...     ...     ...     ...
1555 -0.5700  ... -0.0802 -0.1094 -0.0218 -0.0218 -0.0510 -0.2700 -0.2700
1556 -0.1780  ...  0.3866  0.3334  0.3600  0.5200  0.9200  0.7866  0.5200
1557 -0.3588  ... -0.2760 -0.0798 -0.0920 -0.0184  0.4110  0.4234  0.1288
1558 -0.5548  ...  0.9032  1.0000  0.8870  0.1774  0.1612  0.2580  0.3870
1559 -0.6058  ...  0.5702  0.7520  0.9338  0.5042  0.2396  0.2396  0.3058

         614     615     616
0     0.6410  0.5898 -0.4872
1     0.4318  0.4546 -0.0910
2    -0.0148 -0.3676 -0.7942
3    -0.3648 -0.3648 -0.4864
4    -0.2280 -0.3860 -0.5614
...      ...     ...     ...
1555 -0.2116 -0.2700 -0.4598
1556  0.2000  0.4400  0.1734
1557  0.0184 -0.1902 -0.3988
1558 -0.0646  0.0000 -0.4516
1559  0.3058  0.2066 -0.1240

[1560 rows x 617 columns]>

In [37]:
x= df
y = ff

In [38]:
# data = x_disc
data = x
data['class'] = y
print(data.shape)

(1560, 618)

In [39]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,608,609,610,611,612,613,614,615,616,class
0,-0.4394,-0.0930,0.1718,0.4620,0.6226,0.4704,0.3578,0.0478,-0.1184,-0.2310,...,0.4102,0.2052,0.3846,0.3590,0.5898,0.3334,0.6410,0.5898,-0.4872,1
1,-0.4348,-0.1198,0.2474,0.4036,0.5026,0.6328,0.4948,0.0338,-0.0520,-0.1302,...,0.0000,0.2954,0.2046,0.4772,0.0454,0.2046,0.4318,0.4546,-0.0910,1
2,0.0362,0.7510,0.7188,1.0000,0.9358,0.9840,0.8072,0.4338,0.2290,0.2088,...,0.2206,0.5882,0.4412,-0.1470,-0.0148,0.0294,-0.0148,-0.3676,-0.7942,1
3,0.0220,0.6740,0.6082,0.9122,0.7680,1.0000,0.7932,0.5204,0.1786,0.1568,...,0.1216,0.2162,-0.0270,-0.1352,-0.1756,-0.4730,-0.3648,-0.3648,-0.4864,1
4,-0.9100,-0.3870,-0.3066,0.2048,0.1928,0.6852,0.5644,0.2782,0.1810,0.2072,...,0.0000,-0.2808,-0.4736,-0.3508,-0.3860,-0.4210,-0.2280,-0.3860,-0.5614,1

In [40]:
class_column = 'class'      #might need to edit this depending on dataset's target or class' name
feature_list = data
feature_list =  feature_list.drop(class_column, axis=1)
feature_list = feature_list.columns

x = data[feature_list]
y = data[class_column]

feature_list = data.columns
caim = CAIMD()

x_disc = caim.fit_transform(x, y)
data = x_disc

Categorical [419, 446, 448, 449, 450, 451, 577, 578, 579, 580, 581, 582, 584]
# 0  GLOBAL CAIM  1.6627830045641792
Processed 1 out of 617 features.
# 3  GLOBAL CAIM  2.0605735112000865
Processed 2 out of 617 features.
# 1  GLOBAL CAIM  1.6976873044462066
Processed 3 out of 617 features.
# 2  GLOBAL CAIM  1.9059459305261561
Processed 4 out of 617 features.
# 5  GLOBAL CAIM  2.506104393463279
Processed 5 out of 617 features.
# 6  GLOBAL CAIM  2.641110104048667
Processed 6 out of 617 features.
# 8  GLOBAL CAIM  3.8572799311202393
Processed 7 out of 617 features.
# 4  GLOBAL CAIM  2.248866009357717
Processed 8 out of 617 features.
# 10  GLOBAL CAIM  3.4415236096598423
Processed 9 out of 617 features.
# 9  GLOBAL CAIM  3.892936574478757
Processed 10 out of 617 features.
# 7  GLOBAL CAIM  3.3641994669605477
Processed 11 out of 617 features.
# 11  GLOBAL CAIM  3.6065126476987723
Processed 12 out of 617 features.
# 20  GLOBAL CAIM  2.980149909374665
Processed 13 out of 617 features.
# 13  GLOBAL CAIM  2.284974319497743
Processed 14 out of 617 features.
# 12  GLOBAL CAIM  2.810466329943378
Processed 15 out of 617 features.
# 22  GLOBAL CAIM  3.1161857093387106
Processed 16 out of 617 features.
# 19  GLOBAL CAIM  2.9345503261147305
Processed 17 out of 617 features.
# 17  GLOBAL CAIM  2.52950113893286
Processed 18 out of 617 features.
# 14  GLOBAL CAIM  2.4401022464800852
Processed 19 out of 617 features.
# 23  GLOBAL CAIM  2.858530424287495
Processed 20 out of 617 features.
# 18  GLOBAL CAIM  2.8600549227177217
Processed 21 out of 617 features.
# 21  GLOBAL CAIM  2.9664900293090946
Processed 22 out of 617 features.
# 15  GLOBAL CAIM  2.751087081598254
Processed 23 out of 617 features.
# 16  GLOBAL CAIM  2.416417898272971
Processed 24 out of 617 features.
# 32  GLOBAL CAIM  1.4372720899902907
Processed 25 out of 617 features.
# 24  GLOBAL CAIM  2.515971373618723
Processed 26 out of 617 features.
# 26  GLOBAL CAIM  2.5103556053984235
Processed 27 out of 617 features.
# 29  GLOBAL CAIM  2.3985141889458683
Processed 28 out of 617 features.
# 28  GLOBAL CAIM  2.1089171345916373
Processed 29 out of 617 features.
# 25  GLOBAL CAIM  2.6330455027840136
Processed 30 out of 617 features.
# 31  GLOBAL CAIM  2.304337595269295
Processed 31 out of 617 features.
# 27  GLOBAL CAIM  2.414612372802467
Processed 32 out of 617 features.
# 34  GLOBAL CAIM  1.6249742277124761
Processed 33 out of 617 features.
# 35  GLOBAL CAIM  1.742071186012641
Processed 34 out of 617 features.
# 33  GLOBAL CAIM  1.5341589045350568
Processed 35 out of 617 features.
# 30  GLOBAL CAIM  2.4464712601266894
Processed 36 out of 617 features.
# 36  GLOBAL CAIM  1.7554348125952073
Processed 37 out of 617 features.
# 37  GLOBAL CAIM  2.2297136024313526
Processed 38 out of 617 features.
# 38  GLOBAL CAIM  2.4129963272503563
Processed 39 out of 617 features.
# 46  GLOBAL CAIM  2.255393738419195
Processed 40 out of 617 features.
# 45  GLOBAL CAIM  2.3626781718599594
Processed 41 out of 617 features.
# 39  GLOBAL CAIM  2.765211325388057
Processed 42 out of 617 features.
# 42  GLOBAL CAIM  3.06837340641857
Processed 43 out of 617 features.
# 44  GLOBAL CAIM  2.528574794481593
Processed 44 out of 617 features.
# 41  GLOBAL CAIM  3.326994203769119
Processed 45 out of 617 features.
# 40  GLOBAL CAIM  3.2335722233626734
Processed 46 out of 617 features.
# 43  GLOBAL CAIM  3.3172895954158856
Processed 47 out of 617 features.
# 47  GLOBAL CAIM  2.0967817641781603
Processed 48 out of 617 features.
# 49  GLOBAL CAIM  2.102709293757316
Processed 49 out of 617 features.
# 48  GLOBAL CAIM  2.36237500371199
Processed 50 out of 617 features.
# 54  GLOBAL CAIM  2.167370837202331
Processed 51 out of 617 features.
# 52  GLOBAL CAIM  2.143491200527559
Processed 52 out of 617 features.
# 53  GLOBAL CAIM  2.271558818723674
Processed 53 out of 617 features.
# 51  GLOBAL CAIM  2.3297557451312416
Processed 54 out of 617 features.
# 55  GLOBAL CAIM  2.1875206323388734
Processed 55 out of 617 features.
# 50  GLOBAL CAIM  2.212789047929395
Processed 56 out of 617 features.
# 56  GLOBAL CAIM  2.2669567142184883
Processed 57 out of 617 features.
# 57  GLOBAL CAIM  2.2192560584910814
Processed 58 out of 617 features.
# 58  GLOBAL CAIM  1.9573148066719823
Processed 59 out of 617 features.
# 59  GLOBAL CAIM  1.843367023702034
Processed 60 out of 617 features.
# 62  GLOBAL CAIM  1.773285146253256
Processed 61 out of 617 features.
# 66  GLOBAL CAIM  1.6087523202689922
Processed 62 out of 617 features.
# 64  GLOBAL CAIM  1.4139029131521923
Processed 63 out of 617 features.
# 65  GLOBAL CAIM  1.3067496259331106
Processed 64 out of 617 features.
# 60  GLOBAL CAIM  1.7113355966194037
Processed 65 out of 617 features.
# 61  GLOBAL CAIM  1.6927915313660182
Processed 66 out of 617 features.
# 63  GLOBAL CAIM  1.9336366030967715
Processed 67 out of 617 features.
# 67  GLOBAL CAIM  1.9356461361283974
Processed 68 out of 617 features.
# 68  GLOBAL CAIM  2.0375647659320313
Processed 69 out of 617 features.
# 69  GLOBAL CAIM  2.3855544319592643
Processed 70 out of 617 features.
# 70  GLOBAL CAIM  2.5134113383950965
Processed 71 out of 617 features.
# 71  GLOBAL CAIM  2.665946523049914
Processed 72 out of 617 features.

KeyboardInterrupt:

In [ ]:
data[class_column] = y 
print(data.shape)
data.to_csv(f'../datasets/{datasetFileName.split('.')[0]}_discretized.csv', index=False)